name: credit_card
channels:
  - anaconda
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.2
  - intel-openmp=2020.1
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1g
  - pandas=1.0.4
  - pip=20.1.1
  - python=3.8.3
  - python-dateutil=2.8.1
  - pytz=2020.1
  - readline=8.0
  - setuptools=47.3.0
  - six=1.15.0
  - sqlite=3.32.2
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - docutils==0.16
    - statistics==1.0.3.5
prefix:

